server:
  port: 8080

spring:
  data:
    redis:
      port: 6379
      host: 127.0.0.1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/big_data?characterEncoding=UTF-8
    username: root
    password: qwer1234!
    hikari:
      maximum-pool-size: 40
  graphql:
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql

graphql:
  tools:
    schema-location-pattern: "**/*.graphqls"
#    introspection-enabled: true
  servlet:
    enabled: true
    mapping: /graphql
#    cors-enabled: true
#    cors:
#      allowed-methods: GET, HEAD, POST, PUT, DELETE
      # allowed-origins:
#    exception-handlers-enabled: true
#    context-setting: per_request_with_instrumentation
#    async-mode-enabled: true
